### ISSUE TITLE
Unable to boot after add magisk

### ISSUE THREAD

**Issue by Jiu-xiao** [Geofferey/android_vendor_magisk#1]
I used your patch in the source code. However, I am still stuck in boot animation. I suspect that the encryption of the data partition causes this problem. I fix recovery to be able to use magick normally. I compare the pre and post repair recovery.img It is found that two of these files have been modified. They are partition table files like fstab. The mount option of the /data partition has been changed with the addition of fileencryption option. These two files are only available in recovery_ ramdisk, not in /system.
So what am I going to do, please help me

**Comment by Geofferey** [comment]
Currently this is setup for devices that use recovery as boot system as root. Magisk init should end up in recovery ramdisk which gets made into boot.img but not in a separate recovery.img. If you have a device that has a separate recovery.img (like OnePlus7T) while still using recovery as boot sys as root you may be missing something in BoardConfig.

**Comment by Jiu-xiao** [comment]
There is one thing I don’t understand, what is "make recovery ramdisk into boot.img", whether I need to build boot.img or recovery.img for my device

**Comment by Geofferey** [comment]
On most newer devices recovery ramdisk is included inside of the boot.img instead of a separate recovery.img. With devices that use recovery as boot , system as root the boot.img is actually the recovery image and it just skips recovery (unless told to boot recovery) then loads up ramdisk & init from system partition.... It's all very confusing, I know. What device are you trying this with?

**Comment by Jiu-xiao** [comment]
I understand a little bit now. My device is Huawei Mate10pro, which has a separate recovery_ramdisk partition. Normally, I need to patch recovery.img to implement magisk. So, can my device add magisk without modifying the recovery？
